In [1]:
import numpy as np
import pandas as pd 

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
dataset["Geography"].fillna(dataset["Geography"].mode()[0],inplace = True)
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace = True)
dataset["Age"].fillna(dataset["Age"].mean(),inplace = True)

In [7]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [ ]:
dataset["Geography"].mode()[0]


'France'

In [ ]:
dataset["Age"].mean()

38.924392439243924

In [8]:
dataset.head(1)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1

[1 rows x 14 columns]

In [9]:
dataset["Geography"].unique() 

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
dataset["Gender"].unique() 

array(['Female', 'Male'], dtype=object)

In [11]:
dataset.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Geography"] = le.fit_transform(dataset["Geography"])

dataset["Gender"] = le.fit_transform(dataset["Gender"])




In [13]:
dataset.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave  ...               1        101348.88       1
1          2    15647311      Hill  ...               1        112542.58       0
2          3    15619304      Onio  ...               0        113931.57       1
3          4    15701354      Boni  ...               0         93826.63       0
4          5    15737888  Mitchell  ...               1         79084.10       0
5          6    15574012       Chu  ...               0        149756.71       1
6          7    15592531  Bartlett  ...               1         10062.80       0
7          8    15656148    Obinna  ...               0        119346.88       1
8          9    15792365        He  ...               1         74940.50       0
9         10    15592389        H?  ...               1         71725.73       0

[10 rows x 14 columns]

In [ ]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender   Age  \
0          1    15634602  Hargrave          619          0       0  42.0   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [ ]:
x = dataset.iloc[:,3:13]
y = dataset.iloc[:,13]

In [ ]:
x


CreditScore  Geography  Gender        Age  Tenure    Balance  \
0             619          0       0  42.000000       2       0.00   
1             225          0       0  41.000000       1   83807.86   
2             629          0       0  42.000000       8  159660.80   
3             699          0       0  39.000000       1       0.00   
4             850          2       0  43.000000       2  125510.82   
5             645          2       1  44.000000       8  113755.78   
6             619          0       1  50.000000       7       0.00   
7             376          1       1  38.924392       4  115046.74   
8             501          0       1  44.000000       4  142051.07   
9             684          0       1  43.000000       2  134603.88   
10            528          0       1  31.000000       6  134603.88   
11            497          2       1  24.000000       3       0.00   
12            476          0       0  34.000000      10       0.00   
13            549          0       0  25.000000       5       0.00   
14            635          2       0  35.000000       7       0.00   
15            616          1       1  45.000000       3  143129.41   
16            653          1       1  58.000000       1  132602.88   
17            549          2       0  24.000000       9       0.00   
18            587          2       1  45.000000       6       0.00   
19            726          0       0  24.000000       6       0.00   
20            732          0       1  41.000000       8       0.00   
21            636          2       0  32.000000       8       0.00   
22            510          2       0  38.000000       4       0.00   
23            669          0       1  46.000000       3       0.00   
24            846          0       0  38.000000       5       0.00   
25            577          0       1  25.000000       3       0.00   
26            756          1       1  36.000000       2  136815.64   
27            571          0       1  44.000000       9       0.00   
28            574          1       0  43.000000       3  141349.43   
29            411          0       1  29.000000       0   59697.17   
...           ...        ...     ...        ...     ...        ...   
9970          518          0       1  42.000000       7  151027.05   
9971          833          0       0  34.000000       3  144751.81   
9972          758          0       1  26.000000       4  155739.76   
9973          611          0       1  27.000000       7       0.00   
9974          583          0       1  33.000000       7  122531.86   
9975          610          1       1  50.000000       1  113957.01   
9976          637          0       0  33.000000       7  103377.81   
9977          683          0       0  32.000000       9       0.00   
9978          774          0       1  40.000000       9   93017.47   
9979          677          0       0  58.000000       1   90022.85   
9980          741          2       1  35.000000       6   74371.49   
9981          498          1       1  42.000000       3  152039.70   
9982          655          1       0  46.000000       7  137145.12   
9983          613          0       1  40.000000       4       0.00   
9984          602          1       1  35.000000       7   90602.42   
9985          659          0       1  36.000000       6  123841.49   
9986          673          1       1  47.000000       1  183579.54   
9987          606          2       1  30.000000       8  180307.73   
9988          775          0       1  30.000000       4       0.00   
9989          841          2       1  28.000000       4       0.00   
9990          714          1       1  33.000000       3   35016.60   
9991          597          0       0  53.000000       4   88381.21   
9992          726          2       1  36.000000       2       0.00   
9993          644          0       1  28.000000       7  155060.41   
9994          800          0       0  29.000000       2       0.00   
9995          77

In [ ]:
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
x = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [ ]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [ ]:
x.shape # 10 inputs with 10000 rows

(10000, 10)

In [ ]:
y.shape # 1 column with 10000

(10000,)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(),[1,2])],remainder = "passthrough") # conerts data to binary format
x = ct.fit_transform(x)

In [ ]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [ ]:
x.shape

(10000, 13)

In [ ]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender        Age  \
0          1    15634602  Hargrave          619          0       0  42.000000   
1          2    15647311      Hill          225          0       0  41.000000   
2          3    15619304      Onio          629          0       0  42.000000   
3          4    15701354      Boni          699          0       0  39.000000   
4          5    15737888  Mitchell          850          2       0  43.000000   
5          6    15574012       Chu          645          2       1  44.000000   
6          7    15592531  Bartlett          619          0       1  50.000000   
7          8    15656148    Obinna          376          1       1  38.924392   
8          9    15792365        He          501          0       1  44.000000   
9         10    15592389        H?          684          0       1  43.000000   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [ ]:
x.shape

(10000, 13)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)

#(1, 2,    8000)
#()
#()


In [ ]:
x_train.shape

(8000, 13)

In [ ]:
x_test.shape

(2000, 13)

In [ ]:
x1 = [1,2,3,4,5,6,7,8]
y1 = [1,0,0,0,0,0,0,1]


In [ ]:
for i in range(5):
    x1_train,x1_test,y1_train,y1_test  = train_test_split(x1,y1 , test_size = 0.2 )
    print ("values without random_state", x1_train)

values without random_state [1, 6, 7, 3, 2, 5]
values without random_state [4, 8, 3, 6, 2, 5]
values without random_state [7, 3, 1, 5, 8, 6]
values without random_state [5, 7, 1, 4, 8, 3]
values without random_state [2, 4, 3, 1, 7, 6]


In [ ]:
for i in range(5):
    x1_train,x1_test,y1_train,y1_test  = train_test_split(x1,y1 , test_size = 0.2) # randommseed 
    print ("values wit random_state", x1_train)

values wit random_state [1, 8, 3, 5, 4, 7]
values wit random_state [1, 8, 3, 5, 4, 7]
values wit random_state [1, 8, 3, 5, 4, 7]
values wit random_state [1, 8, 3, 5, 4, 7]
values wit random_state [1, 8, 3, 5, 4, 7]


In [ ]:
#feature scaling is used to vomit the outliers

In [ ]:
a = np.array([[1,2,3],[200,-600,4],[3,7,8]])

In [ ]:
a

array([[   1,    2,    3],
       [ 200, -600,    4],
       [   3,    7,    8]])

In [ ]:
from sklearn.preprocessing import StandardScaler 
sc1 = StandardScaler()
b = sc1.fit_transform(a)# -0.7 1.3#(0,1-1 1)

In [ ]:
b

array([[-0.71779306,  0.69831583, -0.9258201 ],
       [ 1.41415946, -1.41417728, -0.46291005],
       [-0.6963664 ,  0.71586145,  1.38873015]])

In [ ]:
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])