In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv("Fish.csv")

In [4]:
dataset.head(1)

Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream   242.0     23.2     25.4     30.0   11.52   4.02

In [5]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [6]:
dataset.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()
dataset["Species"] = le.fit_transform(dataset["Species"])

In [8]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [9]:
x = dataset.iloc[:,2:7].values

In [10]:
y = dataset.iloc[:,1].values

In [11]:
x.shape

(159, 5)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 , random_state=100)

In [13]:
x_train.shape

(127, 5)

In [14]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
ypred = mlr.predict(x_test)

In [18]:
ypred

array([ 184.36631553,  545.14837775,  949.31467186,  598.17827184,
        472.27893284,  712.67695042,  849.99309399,  364.16968904,
       -147.20005618,  292.78595863,  786.73643058,  -98.82770456,
        680.14445051,  772.89155373,  766.25717535,  165.67210292,
        136.58085862,  148.36655021,  696.85853213,  356.71111924,
        514.06095351,  851.80140973,  152.95935892, -178.30309992,
        200.16942272,  -84.12365942,  885.74744477,  632.70522251,
        708.28294284,   50.15409683,  390.15251313, -161.01919654])

In [20]:
y_test

array([ 160. ,  500. , 1000. ,  600. ,  390. ,  700. ,  770. ,  290. ,
         13.4,  180. ,  955. ,   32. ,  720. , 1000. ,  650. ,  130. ,
        110. ,    0. ,  800. ,  265. ,  390. ,  925. ,  130. ,    9.7,
        140. ,   19.9, 1000. ,  575. ,  850. ,  100. ,  200. ,    9.9])

In [21]:
x_test

array([[20.5   , 22.5   , 25.3   ,  7.0334,  3.8203],
       [28.7   , 31.    , 36.2   , 14.3714,  4.8146],
       [41.1   , 44.    , 46.6   , 12.4888,  7.5958],
       [29.4   , 32.    , 37.2   , 15.438 ,  5.58  ],
       [27.6   , 30.    , 35.    , 12.67  ,  4.69  ],
       [34.5   , 37.    , 39.4   , 10.835 ,  6.2646],
       [44.8   , 48.    , 51.2   ,  7.68  ,  5.376 ],
       [24.    , 26.3   , 31.2   , 12.48  ,  4.3056],
       [11.7   , 12.4   , 13.5   ,  2.43  ,  1.269 ],
       [23.6   , 25.2   , 27.9   ,  7.0866,  3.906 ],
       [35.    , 38.5   , 44.    , 18.084 ,  6.292 ],
       [12.5   , 13.7   , 14.7   ,  3.528 ,  1.9992],
       [32.    , 35.    , 40.6   , 16.3618,  6.09  ],
       [33.5   , 37.    , 42.6   , 18.957 ,  6.603 ],
       [36.5   , 39.    , 41.4   , 11.1366,  6.003 ],
       [20.    , 22.    , 23.5   ,  6.11  ,  3.525 ],
       [19.1   , 20.8   , 23.1   ,  6.1677,  3.3957],
       [19.    , 20.5   , 22.8   ,  6.4752,  3.3516],
       [33.7   , 36.4   , 39

In [22]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)

In [23]:
accuracy

0.8954100039412451

In [24]:
mlr.predict(le.transform[[30,30,30,10,4]])

TypeError: ignored

In [25]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340